#ifndef ADCLINUXDRIVERAPI_H
#define ADCLINUXDRIVERAPI_H
#include <asm/ioctl.h>
#define RGHPADC_IOC_MAGIC  'r'
#define RGHPADC_CONFIG    			_IOW(RGHPADC_IOC_MAGIC, 0, u32)
#define RGHPADC_CHANGEADDRESS 		_IOW(RGHPADC_IOC_MAGIC,  1, u32)
#define RGHPADC_CLEAN_INTERRUPT 	_IOW(RGHPADC_IOC_MAGIC,  2, u32)
#define RGHPADC_LEEARVALORADC 		_IOR(RGHPADC_IOC_MAGIC,  3, u32)

#define RGHPADC_IOC_MAXNR 4


#endif //ADCLINUXDRIVERAPI_H
